import { useCallback, useEffect, useState } from "react";
import { AlertTriangle, Building2, Eye, Filter, Loader2, RefreshCw } from "lucide-react";
import Badge from "../../components/common/Badge";
import GovernmentReportDetailDrawer from "../../components/report/GovernmentReportDetailDrawer";
import { getAdministrativeReports } from "../../services/reportService";
import type { WaterReport, GovReportStatus } from "../../types/report";
import type { Severity } from "../../types/hazard";
import { SEVERITY_STYLES } from "../../types/hazard";

const statuses: { value: GovReportStatus; label: string }[] = [{ value: "under_review", label: "Under Review" }, { value: "assigned", label: "Assigned" }, { value: "in_progress", label: "In Progress" }, { value: "resolved", label: "Resolved" }];
const priorities: Severity[] = ["low", "moderate", "high", "critical"];
const statusLabel = (status?: GovReportStatus) => statuses.find((item) => item.value === status)?.label ?? "Under Review";
const statusVariant = (status?: GovReportStatus): "info" | "warning" | "success" | "neutral" => status === "resolved" ? "success" : status === "in_progress" ? "warning" : status === "assigned" ? "info" : "neutral";

export default function ReviewReports() {
  const [reports, setReports] = useState<WaterReport[]>([]);
  const [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState<WaterReport | null>(null);
  const [filterStatus, setFilterStatus] = useState<GovReportStatus | "all">("all");
  const [filterSeverity, setFilterSeverity] = useState<Severity | "all">("all");
  const load = useCallback(async () => { setLoading(true); try { setReports(await getAdministrativeReports()); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const filtered = reports.filter((r) => (filterStatus === "all" || (r.govStatus ?? "under_review") === filterStatus) && (filterSeverity === "all" || r.severity === filterSeverity));

  return <main className="space-y-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.24em] text-(--color-ocean)">Government Review</p><h1 className="mt-1 text-2xl font-black text-(--color-deep-ocean) sm:text-3xl">Review Reports</h1><p className="mt-1 text-xs text-(--color-medium-teal) sm:text-sm">Review, assign, and update status of citizen-submitted water hazard reports.</p></div><button type="button" onClick={load} className="flex self-start items-center gap-2 rounded-2xl border border-[rgba(53,98,103,0.2)] bg-white px-4 py-2 text-sm font-semibold text-(--color-dark-teal)"><RefreshCw className="h-4 w-4" />Refresh</button></div>
    <section className="rounded-2xl border border-[rgba(53,98,103,0.16)] bg-white p-4 shadow-sm"><div className="mb-3 flex items-center gap-2 text-sm font-bold text-(--color-dark-teal)"><Filter className="h-4 w-4" />Filter Reports</div><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold text-(--color-medium-teal)">Status<select value={filterStatus} onChange={(e) => setFilterStatus(e.target.value as GovReportStatus | "all")} className="mt-1 block w-full rounded-xl border border-[rgba(53,98,103,0.2)] bg-white px-3 py-2 text-sm"><option value="all">All Statuses</option>{statuses.map((x) => <option key={x.value} value={x.value}>{x.label}</option>)}</select></label><label className="text-xs font-semibold text-(--color-medium-teal)">Priority<select value={filterSeverity} onChange={(e) => setFilterSeverity(e.target.value as Severity | "all")} className="mt-1 block w-full rounded-xl border border-[rgba(53,98,103,0.2)] bg-white px-3 py-2 text-sm"><option value="all">All Priorities</option>{priorities.map((x) => <option key={x} value={x}>{SEVERITY_STYLES[x].label}</option>)}</select></label></div></section>
    {loading ? <div className="flex items-center justify-center py-16"><Loader2 className="h-8 w-8 animate-spin text-(--color-ocean)" /><span className="ml-3 text-sm text-(--color-medium-teal)">Loading reports…</span></div> : filtered.length === 0 ? <div className="rounded-3xl border border-[rgba(53,98,103,0.14)] bg-white p-10 text-center"><AlertTriangle className="mx-auto mb-3 h-8 w-8 text-(--color-medium-teal)" /><p className="text-sm text-(--color-medium-teal)">No reports match the selected filters.</p></div> : <><div className="hidden overflow-x-auto rounded-3xl border border-[rgba(53,98,103,0.16)] bg-white shadow-sm md:block"><table className="min-w-full"><thead className="border-b border-[rgba(53,98,103,0.1)] bg-(--color-soft-mint)"><tr>{["Report ID", "Problem", "Location", "Priority", "Status", "Actions"].map((h) => <th key={h} className="px-5 py-3.5 text-left text-xs font-bold uppercase tracking-[0.12em] text-(--color-medium-teal)">{h}</th>)}</tr></thead><tbody className="divide-y divide-[rgba(53,98,103,0.07)]">{filtered.map((r) => <tr key={r.id} className="transition hover:bg-(--color-soft-mint)/40"><td className="px-5 py-3.5 font-mono text-xs font-semibold text-(--color-ocean)">{r.id}</td><td className="px-5 py-3.5 text-sm font-medium text-(--color-deep-ocean)">{r.categoryLabel}</td><td className="px-5 py-3.5 text-xs text-(--color-medium-teal)">{r.location.placeName ?? r.location.address ?? "Unknown"}</td><td className="px-5 py-3.5"><Priority report={r} /></td><td className="px-5 py-3.5"><Badge variant={statusVariant(r.govStatus)}>{statusLabel(r.govStatus)}</Badge></td><td className="px-5 py-3.5"><button type="button" onClick={() => setSelected(r)} className="flex items-center gap-1.5 rounded-lg bg-(--color-ocean) px-3 py-1.5 text-xs font-semibold text-white"><Eye className="h-3.5 w-3.5" />View</button></td></tr>)}</tbody></table></div><div className="space-y-3 md:hidden">{filtered.map((r) => <article key={r.id} className="rounded-3xl border border-[rgba(53,98,103,0.16)] bg-white p-4 shadow-sm"><div className="mb-3 flex items-start justify-between gap-2"><div><p className="font-mono text-xs font-semibold text-(--color-ocean)">{r.id}</p><p className="mt-0.5 text-sm font-bold text-(--color-deep-ocean)">{r.categoryLabel}</p><p className="mt-0.5 text-xs text-(--color-medium-teal)">{r.location.placeName ?? r.location.address ?? "Unknown"}</p></div><div className="flex flex-col items-end gap-1.5"><Priority report={r} /><Badge variant={statusVariant(r.govStatus)}>{statusLabel(r.govStatus)}</Badge></div></div>{r.assignedDepartment && <p className="mb-3 text-xs text-(--color-medium-teal)"><Building2 className="mr-1 inline h-3.5 w-3.5" />{r.assignedDepartment}</p>}<button type="button" onClick={() => setSelected(r)} className="flex w-full items-center justify-center gap-2 rounded-xl bg-(--color-ocean) py-2.5 text-sm font-bold text-white"><Eye className="h-4 w-4" />View / Assign / Update Status</button></article>)}</div></>}
    {selected && <GovernmentReportDetailDrawer report={selected} onClose={() => setSelected(null)} onUpdated={load} />}
  </main>;
}
function Priority({ report }: { report: WaterReport }) { return <span className={`inline-block rounded-full px-2.5 py-1 text-xs font-semibold ${SEVERITY_STYLES[report.severity].bg} ${SEVERITY_STYLES[report.severity].text}`}>{SEVERITY_STYLES[report.severity].label}</span>; }
